# ESP32 VR Haptic Trigger V3 — by alfawalidou / McWall
# GitHub: https://github.com/alfawalidou/esp32-vr-haptic-trigger-v3
# Discord: .mcwall | Telegram: @McWall07
# SPDX-License-Identifier: Apache-2.0

[wokwi]
version = 1
firmware = '.pio/build/trigger-v3-wokwi/firmware.bin'
elf = '.pio/build/trigger-v3-wokwi/firmware.elf'
